### PR TITLE
Collapse course and CourseDetail

### LINKED ISSUE #152: Collapse Course and CourseDetail into one Model
We need to collapse Course and CourseDetail into one table, Course. The model would have:
`Name, Shortname, Version, Moodle Version, Serial, File Path, License, and Source`. This would represent one file which is one course. The details of the course including intended moodle version and file location are all included in said table.

SiteCourse would then be updated to have `SiteFK, CourseFK, and Active`. Future additions to the columns would be useful for having details related to the courses use on a site. The current celery_task_id needs to be removed as we don't use it and there are other, better methods for tracking the task. Another issue should be opened to handle course restore tracking.

### PR DESCRIPTION
**Pull request by justinnoah**
fixes #152

### CODE REVIEW

**Comment by Kennric** [comment]
I don't see a migration to remove the old course_detail table, is that meant to be in this branch?

I believe you are removing the category field from the model, but this is not removed in the migration.

I'd like another set of eyes on this,  just because there are a lot of opportunities for small errors.

**Comment by justinnoah** [comment]
@Kennric ready for more review

**Comment by Kennric** [comment]
This looks pretty good to me, but please have someone else run the migration and double-check - there are a lot of moving parts and it would be easy to miss something.

**Comment by justinnoah** [comment]
Assigned to @Chetco for review

**Comment by Chetco** [comment]
:+1: I've looked over the code and did some testing with a new cookbook using this branch.

**Pull request merged**
