### PR TITLE
Yaml and envvars

### LINKED ISSUE #112: configuration via env vars
To make Docker image deployment much easier, use environment variables for settings. Defaults should be defined in a settings file (see What's Fresh project for an example of using yaml for this, or just use the standard settings.py style), and these defaults should be over-ridden by environment variables of the same name using os.environ['VARIABLE'] values. 

This should allow the app to pick up environment variables set in Docker containers, in production wsgi environments, or to be configured by edding the settings file and not defining any environment variables.

### PR DESCRIPTION
**Pull request by justinnoah**
Fixes #112 

I switched to yaml because I figured that'd be easier to edit than writing python

### CODE REVIEW

**Comment by brutal-chaos** [comment]
@Kennric this should absolutely *not* be merged yet. If we do want to proceed down this path, a corresponding cookbook branch needs to be created first. Then the cookbook needs to have a new version uploaded about the time this is merged to keep staging/prod alive

**Comment by Kennric** [comment]
This looks like the right direction to me. As we work on a general python deploy cookbook, we may find places where we need to adjust.

**Comment by iankronquist** [comment]
@justinnoah What's the status on this?

**Comment by justinnoah** [comment]
@iankronquist it works (or did at the time). @Kennric wanted to wait on either a docker image or the python-for-everything cookbook (I don't recall which now) before we moved ahead with this.

**Comment by Kennric** [comment]
Obsolete, closing

**Pull request closed without merging**
